config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :event_posts

  root 'event_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_post.rb
class EventPost < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>"}
  has_attached_file :image, :default_url => "original/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :event_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_posts_controller.rb
class EventPostsController < ApplicationController
  before_action :find_event_post, only: [:show, :edit, :update, :destroy]

  def index
    @event_posts = EventPost.all.order("created_at DESC")
  end

  def show
  end

  def new
    @event_post = current_user.event_posts.build
  end

  def create
    @event_post = current_user.event_posts.build(post_params)

    if @event_post.save
      redirect_to @event_post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event_post.update(post_params)
      redirect_to @event_post
    else
      render 'edit'
    end
  end

  def destroy
    @event_post.destroy
    redirect_to root_path
  end

  private

  def find_event_post
    @event_post = EventPost.find(params[:id])
  end

  def post_params
    params.required(:event_post).permit(:title, :address, :city, :state, :zip_code, :description, :event_contact_number, :event_contact_email_address, :event_link, :start_date, :end_date, :start_time, :end_time, :place, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_posts_helper.rb
module EventPostsHelper
end

app/views/event_posts/_form.html.haml
= simple_form_for @event_post do |f|
  = f.input :title
  = f.input :place
  = f.input :start_date
  = f.input :start_time
  = f.input :end_date
  = f.input :end_time
  = f.input :address
  = f.input :city
  = f.input :state
  = f.input :zip_code
  = f.input :description
  = f.input :event_contact_number
  = f.input :event_contact_email_address
  = f.input :event_link
  = f.input :image 
  = f.submit

app/views/event_posts/edit.html.haml
%h1 Edit post
= image_tag @event_post.image.url(:medium)
= render 'form'

= link_to "Cancel", event_post_path

app/views/event_posts/index.html.haml
#event_posts
  - @event_posts.each do |event_post|
    .event_post
      %h2= event_post.title
      = image_tag event_post.image.url (:medium)
      %h3= event_post.place
      %p.date= "Start Date #{event_post.start_date} and End Date: #{event_post.end_date}"
      %p= "Start time: #{event_post.start_time} and End time: #{event_post.end_time}"
      %h3= "Description"
      %p= event_post.description
      %p
      Submitted on
      = "#{event_post.created_at} by #{event_post.user.email}"

- @event_posts.each do |event_post|
  %h2= event_post.title
  %h3= event_post.place
  %p= "Start Date #{event_post.start_date} and End Date: #{event_post.end_date}"
  %p= "Start time: #{event_post.start_time} and End time: #{event_post.end_time}"
  %h3 Description
  %p= event_post.description
  %p
  Submitted
  = event_post.created_at
  = event_post.start_date

app/views/event_posts/new.html.haml
%h1 New Post

= render 'form'

app/views/event_posts/show.html.haml
%h1= @event_post.title
%p= image_tag @event_post.image.url (:medium)
%p= "Start date and time: #{@event_post.start_date} and #{@event_post.start_time}"
%p= "End date and time: #{@event_post.end_date} and #{@event_post.end_time}"
%p= "Location/Place: #{@event_post.place}"
%p= "Address: #{@event_post.address} , #{@event_post.city}  #{@event_post.state} #{@event_post.zip_code}"
%p= @event_post.description
%p=  "Number: #{@event_post.event_contact_number}"
%p= "Contact email: #{@event_post.event_contact_email_address}"
%p= "Website: #{@event_post.event_link}"

= link_to "Edit", edit_event_post_path(@event_post)
= link_to "Delete", event_post_path(@event_post), method: :delete, data: { confirm: "Are you sure you want to delete?"}
= link_to "Home", root_path

app/views/layouts/application.haml
!!!
%html
%head
  %title Automatic Newsletter For You
  = csrf_meta_tags
  = stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track': 'reload'
  %link{"rel": "stylesheet", "href": "https://fonts.googleapis.com/css?family=News+Cycle", "type": "text/css"}
  %link{"rel": "stylesheet", "href": "https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css", "type": "text/css"}
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %header.main_header.clearfix
    .wrapper
      #logo
        %p Automatic Newsletter
    #buttons
      = link_to "New Event Post", new_event_post_path

  .wrapper
    %p.notice= notice
    %p.alert= alert

  .wrapper
    = yield